Feat 74 back crud para valor de hora homem
Nine-Tech/nine-tech-back pull request #40
Opened 2023-10-23 11:56 UTC by otavioabreu27

Feature que possibilita a alteração do valor homem hora e a edição de todos os valores pertinentes associados como valor total de subpacotes, pacotes e projeto

2023-10-23 17:04 UTC, jeejinf approved these changes
Testado e aprovado!!!!!!

2023-10-25 10:41 UTC, Miguel-C1 requested changes
Adicionados comentários sobre a parte do cronograma estimado, retorne para o que estava antes, o front end faz a verificação de quando vem vazio o "data" e cria um objeto com base nisso, e o bad_request faz com que ele não entre no .then e caia no catch por ser uma bad_request.

2023-10-25 10:41 UTC, Miguel-C1 commented on NINETECH/src/main/java/com/example/fatec/ninetech/controllers/CronogramaEstimadoController.java
> +              return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(cronogramaEstimado);
Volte essa parte para  "return ResponseEntity.status(HttpStatus.OK).body(cronogramaEstimado);"

2023-10-25 13:54 UTC, Miguel-C1 approved these changes

2023-10-25 13:54 UTC, merged